# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
---
version: 2.1

commands:
  authenticate-gcp:
    steps:
      - run:
          name: Create auth configuration files
          command: |
            GCP_SERVICE_ACCOUNT_EMAIL="ci-service-account@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
            GCP_OIDC_AUDIENCE="projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/${GCP_WORKLOAD_IDENTITY_POOL_ID}/providers/${GCP_OIDC_PROVIDER_ID}"
            GCP_IMPERSONATION_URL="https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${GCP_SERVICE_ACCOUNT_EMAIL}:generateAccessToken"

            mkdir -p ~/.config/gcloud
            echo "${CIRCLE_OIDC_TOKEN}" > $HOME/.config/gcloud/oidc_access_token

            cat >> $HOME/.config/gcloud/application_default_credentials.json \<<- EOF
            {
              "type": "external_account",
              "audience": "//iam.googleapis.com/${GCP_OIDC_AUDIENCE}",
              "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
              "token_url": "https://sts.googleapis.com/v1/token",
              "credential_source": {
                "file": "$HOME/.config/gcloud/oidc_access_token",
                "format": {
                  "type": "text"
                }
              },
              "service_account_impersonation_url": "${GCP_IMPERSONATION_URL}"
            }
            EOF
      - run:
          name: Show the files before auth
          command: |
            cat $HOME/.config/gcloud/application_default_credentials.json
            cat $HOME/.config/gcloud/oidc_access_token
      - run:
          name: Try authenticating with creds
          command: gcloud auth login --verbosity debug --cred-file "$HOME/.config/gcloud/application_default_credentials.json"
      - run:
          name: Set GCP project
          command: gcloud config set project "$GCP_PROJECT_ID"
  deploy-service:
    parameters:
      cloud-run-instance:
        type: string
        default: ${CIRCLE_PROJECT_REPONAME}
    steps:
      - run:
          name: Update the Cloud Run with new image
          command: gcloud run services update <<parameters.cloud-run-instance>> --image="${GCP_AR_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_AR_REPO}/${CIRCLE_PROJECT_REPONAME}:latest" --region="${GCP_AR_REGION}"

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:current
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true # DLC will explicitly cache layers here and try to avoid rebuilding.
      - run:
          name: "Build Docker image"
          command: "docker build . --tag ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
      - run:
          name: Save image as tar
          command: |
            mkdir -p images
            docker image save -o "images/${CIRCLE_PROJECT_REPONAME}_${CIRCLE_SHA1}" "${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
      - persist_to_workspace:
          root: .
          paths:
            - images
  push:
    docker:
      - image: cimg/gcp:2023.12
    steps:
      - authenticate-gcp
      - run:
          name: Set up Docker auth
          command: gcloud auth configure-docker "${GCP_AR_REGION}-docker.pkg.dev"
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: default
      - run:
          name: Load image
          command: |
            docker image load < "images/${CIRCLE_PROJECT_REPONAME}_${CIRCLE_SHA1}"
      - run:
          name: Tag image for Artifact Registry
          command: docker tag "${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}" "${GCP_AR_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_AR_REPO}/${CIRCLE_PROJECT_REPONAME}"
      - run:
          name: Push image for Artifact Registry
          command: docker push "${GCP_AR_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_AR_REPO}/${CIRCLE_PROJECT_REPONAME}"
  deploy-prod:
    docker:
      - image: cimg/gcp:2023.12
    steps:
      - authenticate-gcp
      - deploy-service
  deploy-staging:
    docker:
      - image: cimg/gcp:2023.12
    steps:
      - authenticate-gcp
      - deploy-service:
          cloud-run-instance: "${CIRCLE_PROJECT_REPONAME}-staging"
  
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-deploy:
    jobs:
      - build
      - push:
          requires:
            - build
      - deploy-prod:
          requires:
            - push
          filters:
            branches:
              only: /main/
      - deploy-staging:
          requires:
            - push
          filters:
            branches:
              ignore: /main/

